name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - demo
  pull_request:
    branches:
      - demo

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_TURNSTILE_CONTACT_SITE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_CONTACT_SITE_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_TURNSTILE_CAREER_SITE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_CAREER_SITE_KEY }}" >> .env.local
          echo "TURNSTILE_CONTACT_SECRET_KEY=${{ secrets.TURNSTILE_CONTACT_SECRET_KEY }}" >> .env.local
          echo "TURNSTILE_CAREER_SECRET_KEY=${{ secrets.TURNSTILE_CAREER_SECRET_KEY }}" >> .env.local

      - name: Build
        run: npm run build

      - name: Install Firebase Tools
        run: npm install -g firebase-tools@latest

      - name: Deploy to Firebase
        run: |
          # Deploy and capture the output
          output=$(firebase deploy --only hosting:demo --project ${{ secrets.FIREBASE_PROJECT_ID }} --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" 2>&1) || true
          
          # Check if the output contains successful deployment indicators
          if echo "$output" | grep -q "Deploy complete!"; then
            echo "Deployment successful!"
            exit 0
          else
            # If there are serious errors (not just cleanup policy warnings)
            if echo "$output" | grep -q "Error:" && ! echo "$output" | grep -q "cleanup policy"; then
              echo "Deployment failed with errors:"
              echo "$output"
              exit 1
            else
              echo "Deployment completed with warnings:"
              echo "$output"
              exit 0
            fi
          fi
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FIREBASE_FUNCTIONS_REGION: asia-south1 